#!/bin/bash
# Script to compile TypeScript and unify all .js files into a single .gs file for manual deployment.

# --- CONFIGURATION ---
OUTPUT_FILE="./_DEPLOY/northstarUnified.gs"
OUTPUT_DIR="./dist"
TSCONFIG_FILE="./tsconfig.json"

# --- 1. CLEANUP AND DIRECTORY SETUP ---
rm -rf "$OUTPUT_DIR"
rm -rf "./_DEPLOY"
mkdir -p "$OUTPUT_DIR"
mkdir -p "./_DEPLOY"
echo "--- Cleaned and created fresh output directories."

# --- 2. COMPILATION ---
echo "--- Compiling TypeScript files (TS -> JS) ---"
# *** DEFINITIVE FIX: Use npx to locate the local tsc executable ***
npx tsc --project "$TSCONFIG_FILE" --outDir "$OUTPUT_DIR"
if [ $? -ne 0 ]; then
    echo "❌ ERROR: TypeScript compilation failed. Check your .ts files."
    exit 1
fi

# --- 3. CONCATENATION (Unification) ---
echo "--- Unifying compiled JavaScript files (JS -> GS) ---"

echo "/* --- START OF POLARIS CODEBASE --- */" > "$OUTPUT_FILE"
echo "// DO NOT EDIT THIS FILE DIRECTLY. EDIT THE SOURCE .TS FILES." >> "$OUTPUT_FILE"

find "$OUTPUT_DIR" -name "*.js" | sort | while read FILE; do
    echo "" >> "$OUTPUT_FILE"
    BASE_FILENAME=$(basename "$FILE" .js)
    echo "// FILE: $BASE_FILENAME.ts" >> "$OUTPUT_FILE"
    echo "/* --- BLOCK START --- */" >> "$OUTPUT_FILE"
    
    # Concatenate the content, then remove the '"use strict";' line
    cat "$FILE" | grep -v '\"use strict\"' >> "$OUTPUT_FILE"
    
    echo "/* --- BLOCK END --- */" >> "$OUTPUT_FILE"
done

# --- 4. FINAL CLEANUP ---
CLEANUP_SCRIPT="./scripts/cleanup.sh"
if [ -f "$CLEANUP_SCRIPT" ]; then
    echo "--- Running final cleanup script..."
    "$CLEANUP_SCRIPT"
else
    echo "WARNING: Cleanup script not found at $CLEANUP_SCRIPT. Deployment file may contain TypeScript syntax."
fi


echo "✅ Successfully built and cleaned codebase into $OUTPUT_FILE"
echo "Ready for manual copy-paste deployment into the GAS Editor."
