#!/bin/bash
# Script to compile TypeScript and unify all .js files into a single .gs file for manual deployment.

# --- CONFIGURATION ---
OUTPUT_FILE="./_DEPLOY/northstarUnified.gs"
OUTPUT_DIR="./dist"
TSCONFIG_FILE="./tsconfig.json"
# Path to the locally installed TypeScript Compiler executable
TSC_PATH="../node_modules/.bin/tsc" 

# --- 1. CLEANUP AND DIRECTORY SETUP ---
# Clean out the old deployment and compilation directories
rm -rf "$OUTPUT_DIR"
rm -rf "./_DEPLOY"
mkdir -p "$OUTPUT_DIR"
mkdir -p "./_DEPLOY"
echo "--- Cleaned and created fresh output directories."

# --- 2. COMPILATION ---
echo "--- Compiling TypeScript files (TS -> JS) ---"
# *** MODIFIED LINE: Use the local path to tsc ***
$TSC_PATH --project "$TSCONFIG_FILE" --outDir "$OUTPUT_DIR"
if [ $? -ne 0 ]; then
    echo "❌ ERROR: TypeScript compilation failed. Check your .ts files."
    exit 1
fi

# --- 3. CONCATENATION (Unification) ---
echo "--- Unifying compiled JavaScript files (JS -> GS) ---"

# Start the final unified file
echo "/* --- START OF POLARIS CODEBASE --- */" > "$OUTPUT_FILE"
echo "// DO NOT EDIT THIS FILE DIRECTLY. EDIT THE SOURCE .TS FILES." >> "$OUTPUT_FILE"

# Find all compiled .js files in the output directory and concatenate them.
find "$OUTPUT_DIR" -name "*.js" | sort | while read FILE; do
    echo "" >> "$OUTPUT_FILE"
    BASE_FILENAME=$(basename "$FILE" .js)
    echo "// FILE: $BASE_FILENAME.ts" >> "$OUTPUT_FILE"
    echo "/* --- BLOCK START --- */" >> "$OUTPUT_FILE"
    
    # Concatenate the content, then remove the '"use strict";' line
    cat "$FILE" | grep -v '\"use strict\"' >> "$OUTPUT_FILE"
    
    echo "/* --- BLOCK END --- */" >> "$OUTPUT_FILE"
done

echo "" >> "$OUTPUT_FILE"
echo "/* --- END OF POLARIS CODEBASE --- */" >> "$OUTPUT_FILE"

echo "✅ Successfully unified codebase into $OUTPUT_FILE"
echo "Ready for manual copy-paste deployment into the GAS Editor."
