#!/bin/bash
# Script to compile TypeScript and unify all .js files into a single .gs file for manual deployment.

OUTPUT_FILE="./northstarUnified.gs"
OUTPUT_DIR="./dist"

echo "/* --- START OF POLARIS CODEBASE --- */" > "$OUTPUT_FILE"
echo "// DO NOT EDIT THIS FILE DIRECTLY. EDIT THE SOURCE .TS FILES." >> "$OUTPUT_FILE"

# Find all compiled .js files in the output directory and concatenate them.
# The `sort` command ensures the files are added in alphabetical order, respecting dependencies.
find "$OUTPUT_DIR" -name "*.js" | sort | while read FILE; do
    echo "" >> "$OUTPUT_FILE"
    echo "// FILE: ${FILE##*/}" >> "$OUTPUT_FILE"
    echo "/* --- BLOCK START --- */" >> "$OUTPUT_FILE"
    cat "$FILE" >> "$OUTPUT_FILE"
    echo "/* --- BLOCK END --- */" >> "$OUTPUT_FILE"
done

echo "" >> "$OUTPUT_FILE"
echo "/* --- END OF POLARIS CODEBASE --- */" >> "$OUTPUT_FILE"

echo "✅ Successfully unified codebase into $OUTPUT_FILE"
echo "Ready for manual copy-paste deployment into the Business Account's GAS Editor."
